### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by aboutte** [buger/gor#191]
```
[root@web01 ~]# sudo /usr/local/bin/gor --stats --output-http-stats --input-raw :80 --output-http "http://preview.com" --http-allow-header Host:staging.com --http-allow-url "/api/v2/customer" --http-allow-method GET --http-set-header 'User-Agent: Gor'
Version: 0.9.8
2015/08/18 17:20:38 output_http:latest,mean,max,count,count/second
2015/08/18 17:20:38 output_http:0,0,0,0,0
panic: runtime error: slice bounds out of range

goroutine 23 [running]:
runtime.panic(0x724760, 0x92d02f)
	/goroot/src/pkg/runtime/panic.c:279 +0xf5
github.com/buger/gor/proto.Method(0xc208106000, 0xadd, 0x500000, 0x0, 0x0, 0x0)
	/gopath/src/github.com/buger/gor/proto/proto.go:197 +0x88
main.(*HTTPModifier).Rewrite(0xc2080ec008, 0xc208106000, 0xadd, 0x500000, 0x0, 0x0, 0x0)
	/gopath/src/github.com/buger/gor/http_modifier.go:34 +0x94
main.CopyMulty(0x2af27cd9fff0, 0xc20803eba0, 0xc208036c80, 0x1, 0x1, 0x0, 0x0)
	/gopath/src/github.com/buger/gor/emitter.go:35 +0x181
created by main.Start
	/gopath/src/github.com/buger/gor/emitter.go:11 +0xd5

goroutine 16 [select]:
main.Start(0x0)
	/gopath/src/github.com/buger/gor/emitter.go:15 +0x193
main.main()
	/gopath/src/github.com/buger/gor/gor.go:54 +0x1fe

goroutine 19 [finalizer wait]:
runtime.park(0x424a20, 0x931078, 0x92f2c9)
	/goroot/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x931078, 0x92f2c9)
	/goroot/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/goroot/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/goroot/src/pkg/runtime/proc.c:1445

goroutine 20 [chan receive]:
main.(*RAWInput).listen(0xc20803eba0, 0x7fffa8e4fd26, 0x3)
	/gopath/src/github.com/buger/gor/input_raw.go:47 +0x235
created by main.NewRAWInput
	/gopath/src/github.com/buger/gor/input_raw.go:22 +0x80

goroutine 32 [select]:
github.com/buger/gor/raw_socket_listener.(*Listener).listen(0xc20801aa00)
	/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:70 +0x172
created by github.com/buger/gor/raw_socket_listener.NewListener
	/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:62 +0x165

goroutine 33 [runnable]:
net.(*IPConn).ReadFrom(0xc208042018, 0xc20961a000, 0x10000, 0x10000, 0x10000, 0x10000, 0xc208a3e690, 0x0, 0x0)
	/goroot/src/pkg/net/iprawsock_posix.go:98
github.com/buger/gor/raw_socket_listener.(*Listener).readRAWSocket(0xc20801aa00)
	/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:95 +0x1b3
created by github.com/buger/gor/raw_socket_listener.NewListener
	/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:63 +0x17d

goroutine 21 [sleep]:
time.Sleep(0x12a05f200)
	/tmp/makerelease703080346/go/src/pkg/runtime/time.goc:39 +0x31
main.(*GorStat).reportStats(0xc208025230)
	/gopath/src/github.com/buger/gor/gor_stat.go:64 +0xb6
created by main.NewGorStat
	/gopath/src/github.com/buger/gor/gor_stat.go:31 +0x148

goroutine 22 [chan receive]:
main.(*HTTPOutput).workerMaster(0xc20808e140)
	/gopath/src/github.com/buger/gor/output_http.go:84 +0x47
created by main.NewHTTPOutput
	/gopath/src/github.com/buger/gor/output_http.go:77 +0x17f

goroutine 48 [select]:
main.(*HTTPOutput).startWorker(0xc20808e140)
	/gopath/src/github.com/buger/gor/output_http.go:109 +0x261
created by main.(*HTTPOutput).workerMaster
	/gopath/src/github.com/buger/gor/output_http.go:86 +0x79

goroutine 49 [select]:
main.(*HTTPOutput).startWorker(0xc20808e140)
	/gopath/src/github.com/buger/gor/output_http.go:109 +0x261
created by main.(*HTTPOutput).workerMaster
	/gopath/src/github.com/buger/gor/output_http.go:86 +0x79

goroutine 50 [select]:
main.(*HTTPOutput).startWorker(0xc20808e140)
	/gopath/src/github.com/buger/gor/output_http.go:109 +0x261
created by main.(*HTTPOutput).workerMaster
	/gopath/src/github.com/buger/gor/output_http.go:86 +0x79

goroutine 51 [select]:
main.(*HTTPOutput).startWorker(0xc20808e140)
	/gopath/src/github.com/buger/gor/output_http.go:109 +0x261
created by main.(*HTTPOutput).workerMaster
	/gopath/src/github.com/buger/gor/output_http.go:86 +0x79

goroutine 52 [select]:
main.(*HTTPOutput).startWorker(0xc20808e140)
	/gopath/src/github.com/buger/gor/output_http.go:109 +0x261
created by main.(*HTTPOutput).workerMaster
	/gopath/src/github.com/buger/gor/output_http.go:86 +0x79

goroutine 53 [select]:
main.(*HTTPOutput).startWorker(0xc20808e140)
	/gopath/src/github.com/buger/gor/output_http.go:109 +0x261
created by main.(*HTTPOutput).workerMaster
	/gopath/src/github.com/buger/gor/output_http.go:86 +0x79

goroutine 54 [select]:
main.(*HTTPOutput).startWorker(0xc20808e140)
	/gopath/src/github.com/buger/gor/output_http.go:109 +0x261
created by main.(*HTTPOutput).workerMaster
	/gopath/src/github.com/buger/gor/output_http.go:86 +0x79

goroutine 55 [select]:
main.(*HTTPOutput).startWorker(0xc20808e140)
	/gopath/src/github.com/buger/gor/output_http.go:109 +0x261
created by main.(*HTTPOutput).workerMaster
	/gopath/src/github.com/buger/gor/output_http.go:86 +0x79

goroutine 56 [select]:
main.(*HTTPOutput).startWorker(0xc20808e140)
	/gopath/src/github.com/buger/gor/output_http.go:109 +0x261
created by main.(*HTTPOutput).workerMaster
	/gopath/src/github.com/buger/gor/output_http.go:86 +0x79

goroutine 57 [select]:
main.(*HTTPOutput).startWorker(0xc20808e140)
	/gopath/src/github.com/buger/gor/output_http.go:109 +0x261
created by main.(*HTTPOutput).workerMaster
	/gopath/src/github.com/buger/gor/output_http.go:86 +0x79

goroutine 628 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc20801abe0)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd

goroutine 213 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc2086060a0)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd

goroutine 209 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc208606050)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd

goroutine 537 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc208606230)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd

goroutine 535 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc2086061e0)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd

goroutine 1091 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc20808e370)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd

goroutine 312 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc20801ab90)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd

goroutine 1040 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc208606320)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd

goroutine 530 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc208606190)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd

goroutine 284 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc2086060f0)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd

goroutine 1030 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc20808e320)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd

goroutine 394 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc20808e280)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd

goroutine 393 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc20808e230)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd

goroutine 392 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc20808e0f0)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd

goroutine 391 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc20808e050)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd

goroutine 2116 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc20801ad70)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd

goroutine 418 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc20801ab40)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd

goroutine 319 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc20801aaf0)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd

goroutine 1447 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc2086063c0)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd

goroutine 1350 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc20801acd0)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd

goroutine 938 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc208606370)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd

goroutine 652 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc208606280)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd

goroutine 464 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc208606140)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd

goroutine 1488 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc208606410)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd

goroutine 1608 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc20801ad20)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd

goroutine 1922 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc20808e410)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd

goroutine 1013 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc2086062d0)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd

goroutine 1024 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc20808e2d0)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd

goroutine 629 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc20801ac30)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd

goroutine 1319 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc20801ac80)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd

goroutine 1243 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc20808e3c0)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd

goroutine 1784 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc20808e460)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd

goroutine 2135 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc2086064b0)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd

goroutine 1901 [chan receive]:
github.com/buger/gor/raw_socket_listener.(*TCPMessage).listen(0xc208606460)
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:48 +0x5a
created by github.com/buger/gor/raw_socket_listener.NewTCPMessage
	/gopath/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:40 +0xdd
```

Any ideas what I might be doing wrong?

I am running on RHEL and getting about 60k requests an hour.

**Comment by buger** [comment]
Should be fixed in [0.10.0](https://github.com/buger/gor/releases/tag/0.10.0).
