### ISSUE TITLE
Version: 0.10.1 - panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by ajohnstone** [buger/gor#208]
Detailed error: https://gist.github.com/ajohnstone/31ef58434bb49e7c9b14

This seems to only occur when enabling the elastic search option.
```
panic: runtime error: slice bounds out of range

goroutine 14 [running]:
github.com/buger/gor/proto.header(0xc208d8d800, 0x5f4, 0x5f4, 0xc209062d98, 0x6, 0x8, 0x0, 0x0, 0x0, 0xfd, ...)
        /gopath/src/github.com/buger/gor/proto/proto.go:59 +0x1ae
github.com/buger/gor/proto.Header(0xc208d8d800, 0x5f4, 0x5f4, 0xc209062d98, 0x6, 0x8, 0x0, 0x0, 0x0)
        /gopath/src/github.com/buger/gor/proto/proto.go:66 +0x87
main.(*ESPlugin).ResponseAnalyze(0xc20804c460, 0xc208d8d800, 0x5f4, 0x5f4, 0xc2089ae000, 0xd942, 0x19000, 0xecd8bd040, 0x323fe9b, 0x915920, ...)
        /gopath/src/github.com/buger/gor/elasticsearch.go:131 +0x5b2
main.(*HTTPOutput).sendRequest(0xc20804c410, 0xc2080e01c0, 0xc208d8d800, 0x5f4, 0x5f4)
        /gopath/src/github.com/buger/gor/output_http.go:207 +0x533
main.(*HTTPOutput).startWorker(0xc20804c410)
        /gopath/src/github.com/buger/gor/output_http.go:125 +0x1b9
created by main.(*HTTPOutput).workerMaster
        /gopath/src/github.com/buger/gor/output_http.go:100 +0x7e

goroutine 1 [select]:
main.Start(0x0)
        /gopath/src/github.com/buger/gor/emitter.go:33 +0x339
main.main()
        /gopath/src/github.com/buger/gor/gor.go:52 +0x200

```

**Comment by buger** [comment]
Should fix your issue: https://github.com/buger/gor/pull/210

**Comment by Gonzih** [comment]
Hi, when this fix will be released? I tested master and it works, but release binary does not.
