### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by nikhilo** [buger/gor#257]
```
# ./gor --verbose=true --input-raw :80 --output-file requests.gor --http-allow-url some-identifier
Version: 0.10.1
[DEBUG][PID 18774][1461803067314794549][1461803067314.794434ms] Listening for traffic on: :80
2016/04/27 17:24:45 PANIC: pkg: runtime error: slice bounds out of range /gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:199 (0x5969ee)
/goroot/src/runtime/asm_amd64.s:401 (0x454395)
/goroot/src/runtime/panic.go:387 (0x42ba78)
/goroot/src/runtime/panic.go:18 (0x42ac5e)
/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:237 (0x59425e)
/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:100 (0x592b41)
/goroot/src/runtime/asm_amd64.s:2232 (0x4564b1)

panic: runtime error: slice bounds out of range

goroutine 6 [running]:
github.com/buger/gor/proto.Path(0xc2080c203f, 0x593, 0x4fffc1, 0x0, 0x0, 0x0)
	/gopath/src/github.com/buger/gor/proto/proto.go:109 +0x11e
main.(*HTTPModifier).Rewrite(0xc208032018, 0xc2080c203f, 0x593, 0x4fffc1, 0x0, 0x0, 0x0)
	/gopath/src/github.com/buger/gor/http_modifier.go:67 +0x599
main.CopyMulty(0x7f7a1035b628, 0xc20803cc00, 0xc20802aa30, 0x1, 0x1, 0x0, 0x0)
	/gopath/src/github.com/buger/gor/emitter.go:66 +0x543
created by main.Start
	/gopath/src/github.com/buger/gor/emitter.go:28 +0x447

goroutine 1 [select]:
main.Start(0x0)
	/gopath/src/github.com/buger/gor/emitter.go:33 +0x339
main.main()
	/gopath/src/github.com/buger/gor/gor.go:52 +0x200

goroutine 5 [chan receive]:
main.(*RAWInput).listen(0xc20803cc00, 0x7ffdfbc3b821, 0x3)
	/gopath/src/github.com/buger/gor/input_raw.go:72 +0x40e
created by main.NewRAWInput
	/gopath/src/github.com/buger/gor/input_raw.go:28 +0x119

goroutine 8 [select]:
github.com/buger/gor/raw_socket_listener.(*Listener).listen(0xc2085c2000)
	/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:94 +0x3e6
created by github.com/buger/gor/raw_socket_listener.NewListener
	/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:84 +0x29f

goroutine 9 [runnable]:
github.com/buger/gor/raw_socket_listener.(*Listener).isValidPacket(0xc2085c2000, 0xc208608000, 0xb70, 0x10000, 0xb70)
	/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:167
github.com/buger/gor/raw_socket_listener.(*Listener).readRAWSocket(0xc2085c2000)
	/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:155 +0x5b6
created by github.com/buger/gor/raw_socket_listener.NewListener
	/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:85 +0x2b9
```

I looked at issue #215, but I'm still seeing it on v 0.10.1
please help

Sometimes it continues to intercept with exceptions:

```
Version: 0.10.1
[DEBUG][PID 19413][1461803393653953421][1461803393653.953613ms] Listening for traffic on: :80
2016/04/27 17:29:56 Received packet with same sequence
2016/04/27 17:29:56 Received packet with same sequence
2016/04/27 17:29:56 Received packet with same sequence
2016/04/27 17:29:56 Received packet with same sequence
2016/04/27 17:29:56 Received packet with same sequence
2016/04/27 17:29:56 Received packet with same sequence
2016/04/27 17:29:56 Received packet with same sequence
2016/04/27 17:29:56 Received packet with same sequence
2016/04/27 17:29:56 Received packet with same sequence
2016/04/27 17:30:05 PANIC: pkg: runtime error: slice bounds out of range /gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:199 (0x5969ee)
/goroot/src/runtime/asm_amd64.s:401 (0x454395)
/goroot/src/runtime/panic.go:387 (0x42ba78)
/goroot/src/runtime/panic.go:18 (0x42ac5e)
/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:237 (0x59425e)
/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:100 (0x592b41)
/goroot/src/runtime/asm_amd64.s:2232 (0x4564b1)

2016/04/27 17:30:51 Received packet with same sequence
2016/04/27 17:30:51 Received packet with same sequence
2016/04/27 17:30:51 Received packet with same sequence
2016/04/27 17:30:51 Received packet with same sequence
2016/04/27 17:30:51 Received packet with same sequence
2016/04/27 17:30:51 Received packet with same sequence
2016/04/27 17:30:59 Received packet with same sequence
2016/04/27 17:30:59 Received packet with same sequence
2016/04/27 17:30:59 Received packet with same sequence
2016/04/27 17:30:59 Received packet with same sequence
2016/04/27 17:30:59 Received packet with same sequence
2016/04/27 17:30:59 Received packet with same sequence
2016/04/27 17:30:59 Received packet with same sequence
2016/04/27 17:31:01 PANIC: pkg: runtime error: slice bounds out of range /gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:199 (0x5969ee)
/goroot/src/runtime/asm_amd64.s:401 (0x454395)
/goroot/src/runtime/panic.go:387 (0x42ba78)
/goroot/src/runtime/panic.go:18 (0x42ac5e)
/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:237 (0x59425e)
/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:100 (0x592b41)
/goroot/src/runtime/asm_amd64.s:2232 (0x4564b1)

2016/04/27 17:31:07 Received packet with same sequence
2016/04/27 17:31:07 Received packet with same sequence
2016/04/27 17:31:07 Received packet with same sequence
2016/04/27 17:31:07 Received packet with same sequence
2016/04/27 17:31:07 Received packet with same sequence
2016/04/27 17:31:07 Received packet with same sequence
2016/04/27 17:31:07 Received packet with same sequence
2016/04/27 17:31:07 Received packet with same sequence
2016/04/27 17:31:22 PANIC: pkg: runtime error: slice bounds out of range /gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:199 (0x5969ee)
/goroot/src/runtime/asm_amd64.s:401 (0x454395)
/goroot/src/runtime/panic.go:387 (0x42ba78)
/goroot/src/runtime/panic.go:18 (0x42ac5e)
/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:237 (0x59425e)
/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:100 (0x592b41)
/goroot/src/runtime/asm_amd64.s:2232 (0x4564b1)

2016/04/27 17:31:40 Received packet with same sequence
panic: runtime error: slice bounds out of range

goroutine 6 [running]:
github.com/buger/gor/proto.Path(0xc2080d403f, 0x593, 0x4fffc1, 0x0, 0x0, 0x0)
	/gopath/src/github.com/buger/gor/proto/proto.go:109 +0x11e
main.(*HTTPModifier).Rewrite(0xc208054000, 0xc2080d403f, 0x593, 0x4fffc1, 0x0, 0x0, 0x0)
	/gopath/src/github.com/buger/gor/http_modifier.go:67 +0x599
main.CopyMulty(0x7f0dd2b6d628, 0xc20803cc00, 0xc20802aa30, 0x1, 0x1, 0x0, 0x0)
	/gopath/src/github.com/buger/gor/emitter.go:66 +0x543
created by main.Start
	/gopath/src/github.com/buger/gor/emitter.go:28 +0x447

goroutine 1 [select]:
main.Start(0x0)
	/gopath/src/github.com/buger/gor/emitter.go:33 +0x339
main.main()
	/gopath/src/github.com/buger/gor/gor.go:52 +0x200

goroutine 5 [chan receive]:
main.(*RAWInput).listen(0xc20803cc00, 0x7ffee558e821, 0x3)
	/gopath/src/github.com/buger/gor/input_raw.go:72 +0x40e
created by main.NewRAWInput
	/gopath/src/github.com/buger/gor/input_raw.go:28 +0x119

goroutine 8 [select]:
github.com/buger/gor/raw_socket_listener.(*Listener).listen(0xc2080100e0)
	/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:94 +0x3e6
created by github.com/buger/gor/raw_socket_listener.NewListener
	/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:84 +0x29f

goroutine 9 [IO wait]:
net.(*pollDesc).Wait(0xc208614060, 0x72, 0x0, 0x0)
	/goroot/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208614060, 0x0, 0x0)
	/goroot/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).readFrom(0xc208614000, 0xc208616000, 0x10000, 0x10000, 0x0, 0x0, 0x0, 0x7f0dd2b5dbb0, 0xc20948a000)
	/goroot/src/net/fd_unix.go:269 +0x4a1
net.(*IPConn).ReadFromIP(0xc2080c0010, 0xc208616000, 0x10000, 0x10000, 0x6c8, 0xc20961c000, 0x0, 0x0)
	/goroot/src/net/iprawsock_posix.go:82 +0x124
net.(*IPConn).ReadFrom(0xc2080c0010, 0xc208616000, 0x10000, 0x10000, 0x6c8, 0x0, 0x0, 0x0, 0x0)
	/goroot/src/net/iprawsock_posix.go:102 +0x12e
github.com/buger/gor/raw_socket_listener.(*Listener).readRAWSocket(0xc2080100e0)
	/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:143 +0x2c1
created by github.com/buger/gor/raw_socket_listener.NewListener
	/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:85 +0x2b9

goroutine 143637 [runnable]:
github.com/buger/gor/raw_socket_listener.func·001(0xc20961e000, 0x6c8, 0x6c8)
	/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:159
created by github.com/buger/gor/raw_socket_listener.(*Listener).readRAWSocket
	/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:161 +0x719

goroutine 147804 [runnable]:
github.com/buger/gor/raw_socket_listener.func·001(0xc209000400, 0xb70, 0xb70)
	/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:159
created by github.com/buger/gor/raw_socket_listener.(*Listener).readRAWSocket
	/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:161 +0x719
```

In the last run, it started showing panic messages at 200 requests intercepted. But when it died, it had captured 450 requests.

**Comment by salimane** [comment]
@buger when do think the next version of gor could be released ?

this current bug has already been fixed on master

**Comment by nikhilo** [comment]
@salimane you mean building from source should have the fix ? nice!

**Comment by salimane** [comment]
Yes, building from source should have the fix.

**Comment by buger** [comment]
Released https://github.com/buger/gor/releases/tag/v0.11.0
