### ISSUE TITLE
panic: reflect: Call using string as type int

### ISSUE THREAD

**Issue by nloadholtes** [buger/gor#261]
Hi, following the examples in the readme I ran into that error. Here's what I entered:

```bash
$ ./gor --input-raw :7000 --output-http "http://localhost:8080"                     
Version: 0.11.0
panic: reflect: Call using string as type int

goroutine 1 [running]:
reflect.Value.call(0x8006c0, 0x99aa90, 0x13, 0x8ba750, 0x4, 0xc82001a1e0, 0x3, 0x4, 0x0, 0x0, ...)
        /usr/local/go/src/reflect/value.go:369 +0x74a
reflect.Value.Call(0x8006c0, 0x99aa90, 0x13, 0xc82001a1e0, 0x3, 0x4, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:300 +0xb1
main.registerPlugin(0x8006c0, 0x99aa90, 0xc8209ffe78, 0x3, 0x3)
        /go/src/github.com/buger/gor/plugins.go:50 +0x360
main.InitPlugins()
        /go/src/github.com/buger/gor/plugins.go:88 +0x685
main.main()
        /go/src/github.com/buger/gor/gor.go:38 +0x197

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

```

**Comment by buger** [comment]
Sorry for that, shameless bug! Fixed, released new bug fix version. Thank you!
