### ISSUE TITLE
get two error on centos 6.7 x64 (index out of range and libpcap.so.0.8: cannot open shared object file)

### ISSUE THREAD

**Issue by vus520** [buger/gor#265]
Using x64 0.11.1 binary from https://github.com/buger/gor/releases.

get this error
```shell
[root@kt52 gor-0.11.1]# gor --input-raw :80 --output-file requests.gor
gor: error while loading shared libraries: libpcap.so.0.8: cannot open shared object file: No such file or directory
```
And I build 0.11.1 source get this error

```
[root@kt52 gor-0.11.1]# /opt/gor-0.11.1/gor-0.11.1 --input-raw :80 --output-file requests.gor
Version:
2016/05/03 18:47:31 Received packet with same sequence
panic: runtime error: index out of range

goroutine 13 [running]:
panic(0x8925c0, 0xc82000e0f0)
    /opt/go/src/runtime/panic.go:481 +0x3e6
github.com/buger/gor/raw_socket_listener.(*Listener).readPcap(0xc820448080)
    /opt/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:289 +0x845
created by github.com/buger/gor/raw_socket_listener.NewListener
    /opt/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:113 +0x3ed

```

server info 
```
[root@kt52 gor-0.11.1]# uname -a
Linux kt52 2.6.32-573.el6.x86_64 #1 SMP Thu Jul 23 15:44:03 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@kt52 gor-0.11.1]# cat /etc/centos-release
CentOS release 6.7 (Final)
[root@kt52 gor-0.11.1]# rpm -qa | grep libpcap
libpcap-devel-1.4.0-4.20130826git2dbcaa1.el6.x86_64
libpcap-1.4.0-4.20130826git2dbcaa1.el6.x86_64
```

**Comment by buger** [comment]
Thank you for the report! Just published bugfix release with explanation what it was https://github.com/buger/gor/releases/tag/v0.11.2

**Comment by vus520** [comment]
Nice, it's working now.
