### ISSUE TITLE
Panic when libpcap was not installed...

### ISSUE THREAD

**Issue by hnlq715** [buger/gor#278]
Everything goes well after `libpcap` installed.
But I do think there should be some tips instead of panics.

```
$ uname -a
Linux 2.6.32-358.el6.x86_64 #1 SMP Fri Feb 22 00:31:26 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ ./gor --input-raw :80 --output-file requests.gor
Version: 0.12.1
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x8 pc=0x7acb1e]

runtime stack:
runtime.throw(0xab1940, 0x2a)
	/usr/local/go/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 98 [syscall, locked to thread]:
runtime.cgocall(0x7986b0, 0xc821372ad8, 0xc800000000)
	/usr/local/go/src/runtime/cgocall.go:123 +0x11b fp=0xc821372a88 sp=0xc821372a58
github.com/google/gopacket/pcap._Cfunc_pcap_compile(0x7f0f240009f0, 0xc821270070, 0x7f0f24000d80, 0xffffff00000001, 0x0)
	??:0 +0x41 fp=0xc821372ad8 sp=0xc821372a88
github.com/google/gopacket/pcap.(*Handle).compileBPFFilter(0xc8204e2d00, 0xc821372cb8, 0xb, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/google/gopacket/pcap/pcap.go:472 +0x43f fp=0xc821372ba0 sp=0xc821372ad8
github.com/google/gopacket/pcap.(*Handle).SetBPFFilter(0xc8204e2d00, 0xc821372cb8, 0xb, 0x0, 0x0)
	/go/src/github.com/google/gopacket/pcap/pcap.go:502 +0x88 fp=0xc821372c68 sp=0xc821372ba0
github.com/buger/gor/raw_socket_listener.(*Listener).readPcap.func1(0xc82018c000, 0xc8213260f0, 0xc8213260ce, 0xc821300000, 0x4, 0x0, 0x0, 0xc82132e000, 0x2, 0x2)
	/go/src/github.com/buger/gor/raw_socket_listener/listener.go:296 +0x3f1 fp=0xc821372f60 sp=0xc821372c68
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc821372f68 sp=0xc821372f60
created by github.com/buger/gor/raw_socket_listener.(*Listener).readPcap
	/go/src/github.com/buger/gor/raw_socket_listener/listener.go:378 +0x2f2

goroutine 1 [select]:
github.com/buger/gor/raw_socket_listener.(*Listener).IsReady(0xc82018c000, 0x7fff53e0473d)
	/go/src/github.com/buger/gor/raw_socket_listener/listener.go:587 +0x104
main.NewRAWInput(0x7fff53e0473d, 0x3, 0x2, 0x0, 0xc8204e2b40)
	/go/src/github.com/buger/gor/input_raw.go:36 +0x109
reflect.Value.call(0x92b440, 0xaeed50, 0x13, 0x9f6dd8, 0x4, 0xc820088120, 0x3, 0x4, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x92b440, 0xaeed50, 0x13, 0xc820088120, 0x3, 0x4, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0xb1
main.registerPlugin(0x92b440, 0xaeed50, 0xc820705e10, 0x3, 0x3)
	/go/src/github.com/buger/gor/plugins.go:54 +0x360
main.InitPlugins()
	/go/src/github.com/buger/gor/plugins.go:97 +0x6e7
main.main()
	/go/src/github.com/buger/gor/gor.go:41 +0x1ba

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 20 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 3 [select]:
github.com/buger/gor/raw_socket_listener.(*Listener).listen(0xc82018c000)
	/go/src/github.com/buger/gor/raw_socket_listener/listener.go:130 +0x3dd
created by github.com/buger/gor/raw_socket_listener.NewListener
	/go/src/github.com/buger/gor/raw_socket_listener/listener.go:109 +0x3a6

goroutine 4 [semacquire]:
sync.runtime_Semacquire(0xc8213260fc)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc8213260f0)
	/usr/local/go/src/sync/waitgroup.go:127 +0xb4
github.com/buger/gor/raw_socket_listener.(*Listener).readPcap(0xc82018c000)
	/go/src/github.com/buger/gor/raw_socket_listener/listener.go:381 +0x322
created by github.com/buger/gor/raw_socket_listener.NewListener
	/go/src/github.com/buger/gor/raw_socket_listener/listener.go:117 +0x40f

goroutine 5 [chan receive]:
main.(*RAWInput).listen.func1(0xc8204e2b40, 0xc820088300)
	/go/src/github.com/buger/gor/input_raw.go:81 +0x7a
created by main.(*RAWInput).listen
	/go/src/github.com/buger/gor/input_raw.go:85 +0x385

goroutine 99 [syscall, locked to thread]:
github.com/google/gopacket/pcap._Cfunc_pcap_next_ex(0x7f0f180008e0, 0xc82136a070, 0xc82136a078, 0x0)
	??:0 +0x41
github.com/google/gopacket/pcap.(*Handle).getNextBufPtrLocked(0xc82136a040, 0xc8212f8b70, 0x0, 0x0)
	/go/src/github.com/google/gopacket/pcap/pcap.go:338 +0x329
github.com/google/gopacket/pcap.(*Handle).ReadPacketData(0xc82136a040, 0x0, 0x0, 0x0, 0x0, 0xc800000000, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/google/gopacket/pcap/pcap.go:289 +0xca
github.com/google/gopacket.(*PacketSource).NextPacket(0xc8212f8eb8, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/google/gopacket/packet.go:762 +0x79
github.com/buger/gor/raw_socket_listener.(*Listener).readPcap.func1(0xc82018c000, 0xc8213260f0, 0xc8213260ce, 0xc821326030, 0x4, 0x0, 0x0, 0xc82132e060, 0x2, 0x2)
	/go/src/github.com/buger/gor/raw_socket_listener/listener.go:312 +0x898
created by github.com/buger/gor/raw_socket_listener.(*Listener).readPcap
	/go/src/github.com/buger/gor/raw_socket_listener/listener.go:378 +0x2f2

goroutine 100 [syscall, locked to thread]:
github.com/google/gopacket/pcap._Cfunc_pcap_next_ex(0x7f0f140008e0, 0xc8204e2cb0, 0xc8204e2cb8, 0x0)
	??:0 +0x41
github.com/google/gopacket/pcap.(*Handle).getNextBufPtrLocked(0xc8204e2c80, 0xc820055b70, 0x0, 0x0)
	/go/src/github.com/google/gopacket/pcap/pcap.go:338 +0x329
github.com/google/gopacket/pcap.(*Handle).ReadPacketData(0xc8204e2c80, 0x0, 0x0, 0x0, 0x0, 0x11100000000, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/google/gopacket/pcap/pcap.go:289 +0xca
github.com/google/gopacket.(*PacketSource).NextPacket(0xc820055eb8, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/google/gopacket/packet.go:762 +0x79
github.com/buger/gor/raw_socket_listener.(*Listener).readPcap.func1(0xc82018c000, 0xc8213260f0, 0xc8213260ce, 0xc821326070, 0x2, 0x0, 0x0, 0xc82132e0c0, 0x2, 0x2)
	/go/src/github.com/buger/gor/raw_socket_listener/listener.go:312 +0x898
created by github.com/buger/gor/raw_socket_listener.(*Listener).readPcap
	/go/src/github.com/buger/gor/raw_socket_listener/listener.go:378 +0x2f2
```

**Comment by buger** [comment]
So, just to clarify, before you installed libpcap it panicked, and after installing it is not, right? 

Did you used official Gor binary from releases page, or compiled Gor manually? What is the pcap version  installed on your server? And what is your OS/version?

Thank you!

**Comment by buger** [comment]
Official Gor distributions have libpcap statically linked into binary, and if it panics for you, maybe our version of libpcap (1.7.4) incompatible with your OS.

**Comment by hnlq715** [comment]
@buger Thanks for you reply.
I used the Official Gor distributions from github release page. 

OS version is `CentOS release 6.2 (Final)`.
Libpcap version is `libpcap.x86_64                                        14:1.4.0-4.20130826git2dbcaa1.el6`

**Comment by buger** [comment]
This panic actually tells that it used statically linked libpcap, but internally it failed for some reason. In latest master I added additional protection (seems like it does not like concurrent BPF filter compilation). I will re-open this issues if there will be more bug reports.

**Comment by buger** [comment]
Released https://github.com/buger/gor/releases/tag/v0.13.0 which should address this issue
