### ISSUE TITLE
Intermittant Gor crashes

### ISSUE THREAD

**Issue by Christopher-Bradshaw** [buger/gor#284]
~10% of the time when running gor with:

`sudo GOTRACEBACK=2 gor  -input-raw ':80|3%'  -output-http-url-regexp '/some-regex' -output-file my_file &`

Gor crashes with
```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x9c0 pc=0x7f25da547962]

runtime stack:
runtime.throw(0x9f5f40, 0x2a)
        /usr/local/go/src/runtime/panic.go:547 +0x90 fp=0x7f25d79697a0 sp=0x7f25d7969788
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a fp=0x7f25d79697f0 sp=0x7f25d79697a0

goroutine 11 [syscall, locked to thread]:
runtime.cgocall(0x79a6f0, 0xc8211b6ad8, 0xc800000000)
        /usr/local/go/src/runtime/cgocall.go:123 +0x11b fp=0xc8211b6a88 sp=0xc8211b6a58
github.com/google/gopacket/pcap._Cfunc_pcap_compile(0x7f25cc0009f0, 0xc820b5a050, 0x7f25cc010e40, 0xffff00000001, 0x0)
        ??:0 +0x41 fp=0xc8211b6ad8 sp=0xc8211b6a88
github.com/google/gopacket/pcap.(*Handle).compileBPFFilter(0xc82001a180, 0xc8211b6cb8, 0xb, 0x0, 0x0, 0x0, 0x0)
        /home/vagrant/go/src/github.com/google/gopacket/pcap/pcap.go:472 +0x43f fp=0xc8211b6ba0 sp=0xc8211b6ad8
github.com/google/gopacket/pcap.(*Handle).SetBPFFilter(0xc82001a180, 0xc8211b6cb8, 0xb, 0x0, 0x0)
        /home/vagrant/go/src/github.com/google/gopacket/pcap/pcap.go:502 +0x88 fp=0xc8211b6c68 sp=0xc8211b6ba0
github.com/buger/gor/raw_socket_listener.(*Listener).readPcap.func1(0xc820152280, 0xc82114b3d0, 0xc82114b3a8, 0xc82114b2c0, 0x4, 0x0, 0x0, 0xc82005e540, 0x2, 0x2)
        /home/vagrant/go/src/github.com/buger/gor/raw_socket_listener/listener.go:300 +0x3f1 fp=0xc8211b6f60 sp=0xc8211b6c68
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8211b6f68 sp=0xc8211b6f60
created by github.com/buger/gor/raw_socket_listener.(*Listener).readPcap
        /home/vagrant/go/src/github.com/buger/gor/raw_socket_listener/listener.go:382 +0x2f2
```

I built gor using go1.6.2, on commit 2836b555e3f0507945e7a14c2be7ad6883a636eb
Potentially also related, my version of libpcap is 1.5.3-2 - the latest released for 14.04

**Comment by buger** [comment]
Can you try with this commit https://github.com/buger/gor/commit/98868e81c500579428049944ce47ee50d0ec107b ?

This BPF filter thing is tricky...

**Comment by buger** [comment]
Just released https://github.com/buger/gor/releases/tag/v0.13.0 and it contain this changes (also optional response tracking as you were interested in it before)

**Comment by Christopher-Bradshaw** [comment]
Is working for me, thank-you!
`also optional response tracking as you were interested in it before` - awesome!
