### ISSUE TITLE
PANIC: pkg: runtime error: slice bounds out of range Addr: X�(�

### ISSUE THREAD

**Issue by lucaspouzac** [buger/gor#352]
Hi, 

I observed several panic errors during capture queries.

Version : 100_continue_multi_packet

Can you fix this?

Example : 

```
2016/08/01 18:06:05 PANIC: pkg: runtime error: slice bounds out of range Addr: X�(�
Source port: 7632
Dest port:80
Sequence:313242978
Acknowledgment:394946418
Header len:5
Data size:351
Data:*** goroutine 50 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
github.com/buger/gor/raw_socket_listener.(*Listener).processTCPPacket.func1(0xc821d58c80)
	/go/src/github.com/buger/gor/raw_socket_listener/listener.go:589 +0x75
panic(0x977920, 0xc82000c040)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/buger/gor/proto.header(0xc822bab7a4, 0x5c, 0x5c, 0xc8212319c8, 0xe, 0xe, 0x0, 0x0, 0x0, 0x4c, ...)
	/go/src/github.com/buger/gor/proto/proto.go:158 +0x272
github.com/buger/gor/proto.Header(0xc822bab7a4, 0x5c, 0x5c, 0xc8212319c8, 0xe, 0xe, 0x0, 0x0, 0x0)
	/go/src/github.com/buger/gor/proto/proto.go:165 +0x7d
github.com/buger/gor/raw_socket_listener.(*TCPMessage).updateBodyType(0xc8222051e0)
	/go/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:333 +0x1aa
github.com/buger/gor/raw_socket_listener.(*TCPMessage).AddPacket(0xc8222051e0, 0xc821d58c80)
	/go/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:137 +0x412
github.com/buger/gor/raw_socket_listener.(*Listener).processTCPPacket(0xc82016e000, 0xc821d58c80)
	/go/src/github.com/buger/gor/raw_socket_listener/listener.go:650 +0x728
github.com/buger/gor/raw_socket_listener.(*Listener).listen(0xc82016e000)
	/go/src/github.com/buger/gor/raw_socket_listener/listener.go:144 +0x24b
created by github.com/buger/gor/raw_socket_listener.NewListener
	/go/src/github.com/buger/gor/raw_socket_listener/listener.go:113 +0x3aa
```

```
2016/08/01 18:06:07 output_tcp:0,0,0,231,46,22
2016/08/01 18:06:12 PANIC: pkg: runtime error: slice bounds out of range Addr: X�(�
Source port: 49362
Dest port:80
Sequence:2787614394
Acknowledgment:2355667259
Header len:5
Data size:1808
Data:345
Accept: */*
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safar goroutine 50 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
github.com/buger/gor/raw_socket_listener.(*Listener).processTCPPacket.func1(0xc821bccc00)
	/go/src/github.com/buger/gor/raw_socket_listener/listener.go:589 +0x75
panic(0x977920, 0xc82000c040)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/buger/gor/proto.header(0xc82251ea24, 0x53, 0x53, 0xc8228679d8, 0xe, 0xe, 0x0, 0x0, 0x0, 0x43, ...)
	/go/src/github.com/buger/gor/proto/proto.go:158 +0x272
github.com/buger/gor/proto.Header(0xc82251ea24, 0x53, 0x53, 0xc8228679d8, 0xe, 0xe, 0x0, 0x0, 0x0)
	/go/src/github.com/buger/gor/proto/proto.go:165 +0x7d
github.com/buger/gor/raw_socket_listener.(*TCPMessage).updateBodyType(0xc821bc7080)
	/go/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:333 +0x1aa
github.com/buger/gor/raw_socket_listener.(*TCPMessage).AddPacket(0xc821bc7080, 0xc821bccc00)
	/go/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:137 +0x412
github.com/buger/gor/raw_socket_listener.(*Listener).processTCPPacket(0xc82016e000, 0xc821bccc00)
	/go/src/github.com/buger/gor/raw_socket_listener/listener.go:650 +0x728
github.com/buger/gor/raw_socket_listener.(*Listener).listen(0xc82016e000)
	/go/src/github.com/buger/gor/raw_socket_listener/listener.go:144 +0x24b
created by github.com/buger/gor/raw_socket_listener.NewListener
	/go/src/github.com/buger/gor/raw_socket_listener/listener.go:113 +0x3aa
```

**Comment by buger** [comment]
It seems like it split HTTP packet into multiple TCP packets, and it even split headers in the middle: "345\r\nAccept: */*" (345 is the value from the previous packet). When it reads headers, it should consider that same header can be in 2 packets.

**Comment by buger** [comment]
What is the scope of this issue, how often this happens?

**Comment by lucaspouzac** [comment]
About 5 to 10 errors per minutes

**Comment by lucaspouzac** [comment]
By switching to 100% of traffic I have about 2000 queries per second on error (approximately 50% of all requests)

**Comment by buger** [comment]
It should be fixed in master, here are binaries:

[gor_fix_splitted_headers_mac.tar.gz](https://github.com/buger/gor/files/399586/gor_fix_splitted_headers_mac.tar.gz)
[gor_fix_splitted_headers_x64.tar.gz](https://github.com/buger/gor/files/399587/gor_fix_splitted_headers_x64.tar.gz)

**Comment by lucaspouzac** [comment]
Great. It works perfectly.

**Comment by buger** [comment]
New version  [v0.15.0](https://github.com/buger/gor/releases/tag/v0.15.0) include those fixes.
