### ISSUE TITLE
panic: runtime error: index out of range (gzip mode ?)

### ISSUE THREAD

**Issue by lucaspouzac** [buger/gor#353]
Hi, 

Sometimes, the aggregator gor throws an error. Maybe, the gzip mode ?

```
/usr/sbin/gor --input-tcp :28020 --output-file /var/log/gor/%Y%m%d%H-requests.log.gz --output-file-append
```

```
Version: 100_continue_multi_packet
panic: runtime error: index out of range

goroutine 67 [running]:
panic(0x977920, 0xc820010020)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
compress/flate.(*compressor).findMatch(0xc822362000, 0xba7b, 0xfffffffffffff015, 0x2, 0x4585, 0x2, 0x0, 0xb16800)
	/usr/local/go/src/compress/flate/deflate.go:177 +0x21a
compress/flate.(*compressor).deflate(0xc822362000)
	/usr/local/go/src/compress/flate/deflate.go:286 +0x60e
compress/flate.(*compressor).syncFlush(0xc822362000, 0x0, 0x0)
	/usr/local/go/src/compress/flate/deflate.go:387 +0x40
compress/flate.(*Writer).Flush(0xc822362000, 0x0, 0x0)
	/usr/local/go/src/compress/flate/deflate.go:547 +0x34
compress/gzip.(*Writer).Flush(0xc82248a2c0, 0x0, 0x0)
	/usr/local/go/src/compress/gzip/gzip.go:241 +0xce
main.(*FileOutput).flush(0xc820060240)
	/go/src/github.com/buger/gor/output_file.go:216 +0x148
main.NewFileOutput.func1(0xc820060240)
	/go/src/github.com/buger/gor/output_file.go:59 +0x36
created by main.NewFileOutput
	/go/src/github.com/buger/gor/output_file.go:61 +0x97
```

**Comment by buger** [comment]
Well, it related to gzip format, issue happens inside golang compression library, and very similar to this one https://github.com/golang/go/issues/3998, but it was closed because was hard to replicate :grimacing:

I prepared the patch which will print the error to log, but a process itself will not crash. It could be that it will auto-recover. Try this binaries:

[gor_fix_flush_panic_mac.tar.gz](https://github.com/buger/gor/files/396502/gor_fix_flush_panic_mac.tar.gz)
[gor_fix_flush_panic_x64.tar.gz](https://github.com/buger/gor/files/396503/gor_fix_flush_panic_x64.tar.gz)

**Comment by lucaspouzac** [comment]
ok I try with this binaries. I think that the error is thrown during rotate request log file, but I'm not sure.

**Comment by lucaspouzac** [comment]
Another error.

```
Version: fix_flush_panic
panic: runtime error: index out of range

goroutine 16 [running]:
panic(0x9ae300, 0xc820012030)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
compress/flate.(*huffmanBitWriter).writeBlock(0xc82173c000, 0xc823070000, 0x1484, 0x5800, 0xc8204a0900, 0xc821883270, 0xad90, 0xad90)
	/usr/local/go/src/compress/flate/huffman_bit_writer.go:393 +0xe6a
compress/flate.(*compressor).writeBlock(0xc82008a360, 0xc823070000, 0x1483, 0x5800, 0x10000, 0x0, 0x0, 0x0)
	/usr/local/go/src/compress/flate/deflate.go:142 +0x10e
compress/flate.(*compressor).deflate(0xc82008a360)
	/usr/local/go/src/compress/flate/deflate.go:259 +0x30b
compress/flate.(*compressor).write(0xc82008a360, 0xc8211e43f0, 0x5fb, 0x4ffc10, 0x9eb, 0x0, 0x0)
	/usr/local/go/src/compress/flate/deflate.go:379 +0xb5
compress/flate.(*Writer).Write(0xc82008a360, 0xc8211e4000, 0x9eb, 0x500000, 0x9eb, 0x0, 0x0)
	/usr/local/go/src/compress/flate/deflate.go:534 +0x54
compress/gzip.(*Writer).Write(0xc8200cc210, 0xc8211e4000, 0x9eb, 0x500000, 0x429401, 0x0, 0x0)
	/usr/local/go/src/compress/gzip/gzip.go:216 +0x5ed
main.(*FileOutput).Write(0xc82006a240, 0xc8211e4000, 0x9eb, 0x500000, 0x9eb, 0x0, 0x0)
	/go/src/github.com/buger/gor/output_file.go:203 +0x1a7
main.CopyMulty(0x7ff725dd4e38, 0xc8211b7320, 0xc8211bc6b0, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/buger/gor/emitter.go:94 +0xbfd
created by main.Start
	/go/src/github.com/buger/gor/emitter.go:28 +0x4ae
```

**Comment by lucaspouzac** [comment]
Maybe, you could gzip only during rotate file ?

- 2016080210-requests.log.gz
- 2016080211-requests.log.gz
- 2016080212-requests.log

When gor process crash, the launch of gor overwrites the request file (with and without gzip)

**Comment by lucaspouzac** [comment]
```
2016/08/02 13:10:08 PANIC while file flush:  runtime error: index out of range File output: /var/log/gor/2016080213-requests.log.gz goroutine 35 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
main.(*FileOutput).flush.func1(0xc82006c240)
	/go/src/github.com/buger/gor/output_file.go:215 +0x75
panic(0x9ae300, 0xc820010020)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
compress/flate.(*compressor).findMatch(0xc8224e2240, 0xf337, 0xffffffffffffd9ad, 0x2, 0xcc9, 0x2, 0x0, 0x0)
	/usr/local/go/src/compress/flate/deflate.go:177 +0x21a
compress/flate.(*compressor).deflate(0xc8224e2240)
	/usr/local/go/src/compress/flate/deflate.go:286 +0x60e
compress/flate.(*compressor).syncFlush(0xc8224e2240, 0x0, 0x0)
	/usr/local/go/src/compress/flate/deflate.go:387 +0x40
compress/flate.(*Writer).Flush(0xc8224e2240, 0x0, 0x0)
	/usr/local/go/src/compress/flate/deflate.go:547 +0x34
compress/gzip.(*Writer).Flush(0xc8200e0a50, 0x0, 0x0)
	/usr/local/go/src/compress/gzip/gzip.go:241 +0xce
main.(*FileOutput).flush(0xc82006c240)
	/go/src/github.com/buger/gor/output_file.go:224 +0x176
main.NewFileOutput.func1(0xc82006c240)
	/go/src/github.com/buger/gor/output_file.go:60 +0x36
created by main.NewFileOutput
	/go/src/github.com/buger/gor/output_file.go:62 +0x97
```

**Comment by buger** [comment]
I made few fixes, hope it helps: 
[gor_disable_forced_flush_mac.tar.gz](https://github.com/buger/gor/files/407105/gor_disable_forced_flush_mac.tar.gz)
[gor_disable_forced_flush_x64.tar.gz](https://github.com/buger/gor/files/407104/gor_disable_forced_flush_x64.tar.gz)

**Comment by lucaspouzac** [comment]
No problems found with the latest version (v0.15). Thanks.
